### ISSUE TITLE
Support for LLamma3.2 on Qualcomm A100

### ISSUE THREAD

**Issue by alew3** [quic/cloud-ai-sdk#12]
Do you plan on supporting Llama3.2 (text/multimodal) on Qualcomm A100?
I saw this post (https://www.qualcomm.com/news/onq/2024/09/qualcomm-partners-with-meta-to-support-llama-3-point-2-big-deal-for-on-device-ai) , but it seems to have compatibility only for Snapdragon chips.

**Comment by groundsada** [comment]
Hi @alew3 I am curious to know whether you were able to load up llama3.2 on the Cloud AI 100
